some classes can't be loaded due to some resources they need themselves hence a NoClassDefFoundError will be thrown. This should not stop the program from running.